apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudcart
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/dharshanworks/CloudCart
    targetRevision: main
    path: helm/cloudcart

  destination:
    server: https://kubernetes.default.svc
    namespace: cloudcart

  syncPolicy:
    automated:
      prune: true
      selfHeal: true