apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloudcart-ingress
  namespace: cloudcart
spec:
  ingressClassName: nginx
  rules:
  - host: cloudcart.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cloudcart-frontend-service
            port:
              number: 80