services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    container_name: cloudcart-backend

    ports:
      - "5001:5000"

    env_file:
      - ./backend/.env

    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    container_name: cloudcart-frontend

    ports:
      - "3000:80"

    depends_on:
      - backend

    restart: unless-stopped