apiVersion: v1
kind: Secret

metadata:
  name: cloudcart-secret
  namespace: cloudcart

type: Opaque

stringData:
  MONGO_URI: "mongodb+srv://cloudcartadmin:7339386072_dharshan774923@cloudcart-cluster.1vxmjtm.mongodb.net/?appName=cloudcart-cluster"
  JWT_SECRET: "cloudcart_super_secret_key"