apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcart-backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: cloudcart-backend

  template:
    metadata:
      labels:
        app: cloudcart-backend

    spec:
      containers:
        - name: backend

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"

          ports:
            - containerPort: {{ .Values.backend.port }}

          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: cloudcart-config
                  key: PORT

            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: cloudcart-config
                  key: NODE_ENV

            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: cloudcart-secret
                  key: MONGO_URI

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: cloudcart-secret
                  key: JWT_SECRET