apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloudcart-frontend

spec:
  replicas: {{ .Values.frontend.replicas }}

  selector:
    matchLabels:
      app: cloudcart-frontend

  template:
    metadata:
      labels:
        app: cloudcart-frontend

    spec:
      containers:
        - name: frontend

          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"

          imagePullPolicy: Always

          ports:
            - containerPort: {{ .Values.frontend.port }}